-- ============================================================
-- CAD Waitlist — Supabase schema
-- Run this ONCE: Supabase Dashboard → SQL Editor → New query
--   → paste everything below → Run
-- ============================================================

create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  store text not null,
  source text not null default 'landing',
  signed_up_at timestamptz not null default now()
);

alter table public.waitlist enable row level security;

-- Visitors may JOIN the waitlist (insert only) — they cannot read anyone's data
create policy "anon can join waitlist"
on public.waitlist for insert
to anon
with check (true);

-- Count function for the "You're #N in line" badge (no data exposed)
create or replace function public.waitlist_count()
returns bigint
language sql
security definer
set search_path = public
as $$
  select count(*) from public.waitlist;
$$;

grant execute on function public.waitlist_count() to anon;

-- ============================================================
-- Getting the data into Excel:
--   Option A (quick): Supabase Dashboard → Table Editor → waitlist
--                     → "Download CSV" → opens directly in Excel
--   Option B (button): open /admin.html on the deployed site,
--                     paste your service_role key, click
--                     "Download Excel (.xlsx)"
-- ============================================================
